#!/usr/bin/env python3

import time
import hashlib
import hmac
import base64
import sys
import logging
import json
import requests
import uuid

# open token 
token = '' # copy and paste from the SwitchBot app V6.14 or later
# secret key
secret = '' # copy and paste from the SwitchBot app V6.14 or later
nonce = str(uuid.uuid4())
t = int(round(time.time() * 1000))
string_to_sign = '{}{}{}'.format(token, t, nonce)
string_to_sign = bytes(string_to_sign, 'utf-8')
secret = bytes(secret, 'utf-8')
sign = base64.b64encode(hmac.new(secret, msg=string_to_sign, digestmod=hashlib.sha256).digest())
sign =sign.upper();
#print ('Authorization: {}'.format(token))
#print ('t: {}'.format(t))
#print ('sign: {}'.format(str(sign, 'utf-8')))
#print ('nonce: {}'.format(nonce))

header={'Authorization' :token,'t' :str(t),'sign' :str(sign, 'utf-8'),'nonce' :nonce, 'content-type' : 'application/json; charset=utf8'}
#print(header)
r = requests.get("https://api.switch-bot.com/v1.1/devices", params = {'t' :str(t),'sign' :str(sign, 'utf-8'),'nonce' :nonce}, headers = header)

if r.status_code != 200:
    print(r.status_code)
else:
    print(r.json())
 
